### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by mtorromeo** [NDrive/sentry-mattermost#1]
Hi,
it would be nice to have this available on PyPI so that we could install simply with `pip install sentry_mattermost` and update it automatically when a new version is released.

Since you have already a working setup.py, if you have a PyPI account you should be able to publish it simply with:

```sh
python setup.py register
python setup.py sdist upload
```

Thanks

**Comment by andrefreitas** [comment]
Hi @mtorromeo, thanks for reporting this. I just uploaded the package to Pypi :)

https://pypi.python.org/pypi/sentry_mattermost
